### ISSUE TITLE
Flags are not showing

### ISSUE THREAD

**Issue by ayushi-idexcel** [kondi0/ng4-intl-phone#44]
http://res.cloudinary.com/dvbuhh0bl/image/upload/v1495279723/flags_boi3c5.png  ==>> by using ng4-intl-phone as package we are not getting a flag icon

**Comment by sohaieb** [comment]
I really agree with you

**Comment by willyguevara** [comment]
Im having the same issue too, it seems that the resource file doesn't exists anymore.

https://res.cloudinary.com/dvbuhh0bl/image/upload/v1495279723/flags_boi3c5.png

**Comment by Ali-Alzantot** [comment]
same with me

**Comment by andre-gois** [comment]
A quick and dirty solution: 
I found the image on google images:
![flags_boi3c5](https://user-images.githubusercontent.com/8902376/96334980-a6730400-106c-11eb-9bc1-44d3ffa4fa05.jpeg)

Add the file to your assets folder, then add this to your global css file to override the package rule:
`.flagInput .flag {
    background-image: url('/[your path]/flags_boi3c5.jpeg') !important;
}`

**Comment by a7md3bdelfatta7** [comment]
> A quick and dirty solution:
> I found the image on google images:
> ![flags_boi3c5](https://user-images.githubusercontent.com/8902376/96334980-a6730400-106c-11eb-9bc1-44d3ffa4fa05.jpeg)
> 
> Add the file to your assets folder, then add this to your global css file to override the package rule:
> `.flagInput .flag { background-image: url('/[your path]/flags_boi3c5.jpeg') !important; }`

I was thinking for same solution but i couldn't find flags image , thank you.

**Comment by kondi0** [comment]
Sorry guys, I was away for a while. Fixed with angular 14 version
