### ISSUE TITLE
I get submit form when press on flag icon

### ISSUE THREAD

**Issue by nbtai** [kondi0/ng4-intl-phone#7]
When I import `<int-phone-prefix [(ngModel)]="phoneNumber"></int-phone-prefix>`
Then in template, I press the flag button. The form was submitted?

![screenshot from 2017-10-30 09 58 49](https://user-images.githubusercontent.com/7741657/32152835-0182cf16-bd59-11e7-912b-8d8e977bd94d.png)

**Comment by nbtai** [comment]
I check in html. This is a button.
![screenshot from 2017-10-30 10 00 48](https://user-images.githubusercontent.com/7741657/32152871-453a9590-bd59-11e7-81e1-d8ac9cb4c482.png)

**Comment by kondi0** [comment]
I've just pushed new changes where the problem doesn't appear. 

Please, update to version 1.1.3

Regards!
